# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Fighter.destroy_all
User.destroy_all
Match.destroy_all
Challenger.destroy_all

f1 = Fighter.create(first_name: 'Stipe', last_name: 'Miocic', weight: 240, height: 77, champion_status: true, img_url: "https://drive.google.com/file/d/1qCnk1aGyL8UC4D1RLWPbR5oqZoOza-aS/view")
f2 = Fighter.create(first_name: 'Daniel', last_name: 'Cormier', weight: 250, height: 71, champion_status: false, img_url:"https://drive.google.com/file/d/1qCI1_JVDFhO0vZQNnrBPjIVB8hpZJthx/view")
f3 = Fighter.create(first_name: 'Dan', last_name: 'Hornbuckle',weight: 170, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1H1Y67vbP1ZTB1ALuZY4-BrAelRtrrUhL/view")
f4 = Fighter.create(first_name: 'Jose', last_name: 'Aldo',weight: 145, height: 67, champion_status: false, img_url:"https://drive.google.com/file/d/1iDnIr2En4pNArmc22zFmfhuFMEmoGXeO/view")
f5 = Fighter.create(first_name: 'Dominick', last_name: 'Cruz',weight: 135, height: 68, champion_status: false, img_url:"https://drive.google.com/file/d/1XJM2S3ELh--osaB9OP2ns5YsFvVl8hcw/view")
f6 = Fighter.create(first_name: 'Jon', last_name: 'Jones',weight: 205, height: 76, champion_status: true, img_url:"https://drive.google.com/file/d/1pUXrVV1Bv5QX2IfxVLsvG0AIAX1ZXeOO/view")
f7 = Fighter.create(first_name: 'Georges', last_name: 'St-Pierre',weight: 170, height: 70, champion_status: false, img_url:"https://drive.google.com/file/d/1jIJ0VAn5eL9xILXv19zD5vKOYiC0BY3u/view")
f8 = Fighter.create(first_name: 'Junior', last_name: 'dos Santos',weight: 236, height: 76, champion_status: false, img_url:"https://drive.google.com/file/d/19SPMHJHNsWC_PJHMSfpzcB9MKGVake9J/view")
f9 = Fighter.create(first_name: 'Anderson', last_name: 'Silva',weight: 185, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1Z2s5w0YqEZHKeizVY093rhN0CJAi1ZhN/view")
f10 = Fighter.create(first_name: 'Dan', last_name: 'Henderson',weight: 185, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1hXNK0c1yacED6MwFQ9QY-7cekkRhEfEC/view")
f11 = Fighter.create(first_name: 'Antonio', last_name: 'Nogueira',weight: 240, height: 75, champion_status: false, img_url:"https://drive.google.com/file/d/1n5ft6u1L6E49ptq32V6ErFjZp-OW0KFP/view")
f12 = Fighter.create(first_name: 'Matt', last_name: 'Hughes',weight: 170, height: 69, champion_status: false, img_url:"https://drive.google.com/file/d/1EYfZBrOvhxpGuLBPRb_qq45jsVV7yduf/view")
f13 = Fighter.create(first_name: 'Chuck', last_name: 'Liddell',weight: 205, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1UGZPdXNuAU0SizDCisFnkiSiWEeJlIaY/view")
f14 = Fighter.create(first_name: 'Masakatsu', last_name: 'Funaki',weight: 209, height: 72, champion_status: false, img_url:"https://drive.google.com/file/d/16fXb_M5ImW2p-0efH24WmqFeV_MYwQh1/view")
f15 = Fighter.create(first_name: 'Alistair', last_name: 'Overeem',weight: 260, height: 76, champion_status: false, img_url:"https://drive.google.com/file/d/1ifuK2LbyHQTXy0mkTIuAuWxDntZvZnR8/view")
f15 = Fighter.create(first_name: 'Francis', last_name: 'Ngannou',weight: 250, height: 76, champion_status: false, img_url:"https://drive.google.com/file/d/14QamItPoy7tdqFKsYfm5UzkTj-wizITX/view")
f16 = Fighter.create(first_name: 'Fedor', last_name: 'Emelianenko',weight: 223, height: 72, champion_status: false, img_url:"https://drive.google.com/file/d/1LNbziguzI7ogyl6_jnUiSQM89NzKQFGF/view")
f17 = Fighter.create(first_name: 'Randy', last_name: 'Couture',weight: 203, height: 61, champion_status: false, img_url:"https://drive.google.com/file/d/1BO6h7gmthyagNEbHnO4q7cfA3RBbnjiu/view")
f18 = Fighter.create(first_name: 'Nick', last_name: 'Diaz',weight: 155, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1k_O4XtlDyOFGfQaCQPrQb3g0H9qfJ0rC/view")
f19 = Fighter.create(first_name: 'Kamaru', last_name: 'Usman',weight: 170, height: 72, champion_status: true, img_url:"https://drive.google.com/file/d/1Dz_aLvuPvHGuwJu1rIK2FK1xXM0Ff-c4/view")
f20 = Fighter.create(first_name: 'Lyoto', last_name: 'Machida',weight: 185, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1WJ7moDbxj8APH_vrQr2s9FytPsvIpme_/view")
f21 = Fighter.create(first_name: 'Vitor', last_name: 'Belfort',weight: 185, height: 72, champion_status: false, img_url:"https://drive.google.com/file/d/1qrF7KAKnxU0-AJ-NSw4b8dwWdHlftFpi/view")
f22 = Fighter.create(first_name: 'Tim', last_name: 'Sylvia',weight: 265, height: 80, champion_status: false, img_url:"https://drive.google.com/file/d/1elRMpqFzudoUHsOJQDdKXmQn-K3qzXX1/view")
f23 = Fighter.create(first_name: 'Royce', last_name: 'Gracie',weight: 176, height: 72, champion_status: false, img_url:"https://drive.google.com/file/d/15997PfQisTlNR3bAaQ-X6557WGCnndao/view")
f24 = Fighter.create(first_name: 'BJ', last_name: 'Penn',weight: 145, height: 69, champion_status: false, img_url:"https://drive.google.com/file/d/1CkxxtwZdE1eRJ9q-ZpChT2wCTxAkgYcC/view")
f25 = Fighter.create(first_name: 'Rich', last_name: 'Franklin',weight: 185, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1ByLTF-ehv8OB251meWTPF7TgRg74uXUZ/view")
f26 = Fighter.create(first_name: 'Bas', last_name: 'Rutten',weight: 205, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1cigxGKvNADxS5glOwO9EW1tFOGdW4OcV/view")
f27 = Fighter.create(first_name: 'Israel', last_name: 'Adesanya',weight: 185, height: 76, champion_status: true, img_url:"https://drive.google.com/file/d/1en4m_ToIyeiBwEAlUK3_qGmwRfE_TmYu/view")
f28 = Fighter.create(first_name: 'Khabib', last_name: 'Nurmagomedov',weight: 155, height: 70, champion_status: true, img_url:"https://drive.google.com/file/d/17Oy6eGWZ6L_rjfRPTlDHbjFROArr0X4d/view")
f29 = Fighter.create(first_name: 'Justin', last_name: 'Gaethje',weight: 155, height: 71, champion_status: false, img_url:"https://drive.google.com/file/d/1io9fpOB7_2MOmt41Krqd_MZOtqLERHnf/view")
f30 = Fighter.create(first_name: 'Tony', last_name: 'Ferguson',weight: 155, height: 71, champion_status: false, img_url:"https://drive.google.com/file/d/1hB22F0ZVcnV2bLKTrzQyTpM8OSqFSZVm/view")
f31 = Fighter.create(first_name: 'Conor', last_name: 'McGregor',weight: 145, height: 69, champion_status: false, img_url:"https://drive.google.com/file/d/1RpHY8wigkmhBIdo8kOf0lspeTZxKb7_N/view")
f32 = Fighter.create(first_name: 'Demetrius', last_name: 'Johnson',weight: 135, height: 63, champion_status: false, img_url:"https://drive.google.com/file/d/1oV0rfI3VFLH35kOp3S4zXG7VoohX9TNN/view")
f33 = Fighter.create(first_name: 'Max', last_name: 'Holloway',weight: 146, height: 71, champion_status: false, img_url:"https://drive.google.com/file/d/16BQFpWsHavfnW73akIeVVEC4b299FzaE/view")
f34 = Fighter.create(first_name: 'Alex', last_name: 'Volkanovski',weight: 145, height: 66, champion_status: false, img_url:"https://drive.google.com/file/d/1JRE-EKePCKhzQYeXZN7mHrG7g1kMWWM2/view")
f35 = Fighter.create(first_name: 'Edson', last_name: 'Barboza',weight: 155, height: 71, champion_status: false, img_url:"https://drive.google.com/file/d/1EW06h_RkVpUzvyUsmVnPhCfRLvljNMMO/view")
f36 = Fighter.create(first_name: 'Henry', last_name: 'Cejudo',weight: 135, height: 64, champion_status: true, img_url:"https://drive.google.com/file/d/1OLuILqd4ZNAKr5RU1emxjxn99_7s9TBr/view")
f37 = Fighter.create(first_name: 'Frankie', last_name: 'Edgar',weight: 145, height: 66, champion_status: false, img_url:"https://drive.google.com/file/d/131Pj6T6g_IRjdN0zVFDPmLAHwvPLWLJa/view")
f38 = Fighter.create(first_name: 'Eddie', last_name: 'Alvarez',weight: 155, height: 69, champion_status: false, img_url:"https://drive.google.com/file/d/1Zx8wtKJp2r3rPyRny-TO91AF0GeZyk6A/view")
f39 = Fighter.create(first_name: 'Zabit', last_name: 'Magomedsharipov',weight: 145, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1pTF4CYzPJq0T7vk821o6U7udhjPzJv7d/view")
f40 = Fighter.create(first_name: 'Islam', last_name: 'Makhachev',weight: 155, height: 70, champion_status: false, img_url:"https://drive.google.com/file/d/1kQR_LZR725J39rdDyRFtJO-8VgYz47O6/view")
f41 = Fighter.create(first_name: 'Alexander', last_name: 'Volkov',weight: 250, height: 79, champion_status: false, img_url:"https://drive.google.com/file/d/1e0An-4xoxOBtIOrVNnSZlefMAt6Hu3Vo/view")
f42 = Fighter.create(first_name: 'Dominick', last_name: 'Reyes',weight: 205, height: 76, champion_status: false, img_url:"https://drive.google.com/file/d/1nTDCMnK8ZiZCaeOiyPEWK16spvMHT0V2/view")
f43 = Fighter.create(first_name: 'Paulo', last_name: 'Costa',weight: 185, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/12ItG9zSGEYEwstj8IJCTAJnOuWlaW2q0/view")
f44 = Fighter.create(first_name: 'Tyron', last_name: 'Woodley',weight: 170, height: 69, champion_status: false, img_url:"https://drive.google.com/file/d/1liiuDUZQZi2Rds27JoHfZNM6TE2fiXMc/view")
f45 = Fighter.create(first_name: 'Takanori', last_name: 'Gomi',weight: 155, height: 68, champion_status: false, img_url:"https://drive.google.com/file/d/1dAB8WrLMHHiK-OyaV91i64oz9mzQHJEZ/view")
f46 = Fighter.create(first_name: 'Thiago', last_name: 'Santos',weight: 185, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1z72KC5nQyEr8tqEQTHBadjx80yhhAy6Q/view")
f47 = Fighter.create(first_name: 'Marlon', last_name: 'Moraes',weight: 135, height: 66, champion_status: false, img_url:"https://drive.google.com/file/d/1DUxLKGj0fyKWVeKLw6ZlgYxms0Oq287x/view")
f48 = Fighter.create(first_name: 'Cain', last_name: 'Velasquez',weight: 243, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1NDgoIkLXqMOUu0m3EtbQTfpeomXNiMvs/view")
f49 = Fighter.create(first_name: 'Chris', last_name: 'Weidman',weight: 186, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1QxoDntkOsu0NXG4XF5GVC4cyFRkCYtcZ/view")
f50 = Fighter.create(first_name: 'Gegard', last_name: 'Mousasi',weight: 185, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1mBme_R-C99OKpZyA77_WHdZs6kLlwfcv/view")

c1 = Challenger.create(first_name: 'Stipe', last_name: 'Miocic', weight: 240, height: 77, champion_status: true, img_url: "https://drive.google.com/file/d/1qCnk1aGyL8UC4D1RLWPbR5oqZoOza-aS/view")
c2 = Challenger.create(first_name: 'Daniel', last_name: 'Cormier', weight: 250, height: 71, champion_status: false, img_url:"https://drive.google.com/file/d/1qCI1_JVDFhO0vZQNnrBPjIVB8hpZJthx/view")
c3 = Challenger.create(first_name: 'Dan', last_name: 'Hornbuckle',weight: 170, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1H1Y67vbP1ZTB1ALuZY4-BrAelRtrrUhL/view")
c4 = Challenger.create(first_name: 'Jose', last_name: 'Aldo',weight: 145, height: 67, champion_status: false, img_url:"https://drive.google.com/file/d/1iDnIr2En4pNArmc22zFmfhuFMEmoGXeO/view")
c5 = Challenger.create(first_name: 'Dominick', last_name: 'Cruz',weight: 135, height: 68, champion_status: false, img_url:"https://drive.google.com/file/d/1XJM2S3ELh--osaB9OP2ns5YsFvVl8hcw/view")
c6 = Challenger.create(first_name: 'Jon', last_name: 'Jones',weight: 205, height: 76, champion_status: true, img_url:"https://drive.google.com/file/d/1pUXrVV1Bv5QX2IfxVLsvG0AIAX1ZXeOO/view")
c7 = Challenger.create(first_name: 'Georges', last_name: 'St-Pierre',weight: 170, height: 70, champion_status: false, img_url:"https://drive.google.com/file/d/1jIJ0VAn5eL9xILXv19zD5vKOYiC0BY3u/view")
c8 = Challenger.create(first_name: 'Junior', last_name: 'dos Santos',weight: 236, height: 76, champion_status: false, img_url:"https://drive.google.com/file/d/19SPMHJHNsWC_PJHMSfpzcB9MKGVake9J/view")
c9 = Challenger.create(first_name: 'Anderson', last_name: 'Silva',weight: 185, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1Z2s5w0YqEZHKeizVY093rhN0CJAi1ZhN/view")
c10 = Challenger.create(first_name: 'Dan', last_name: 'Henderson',weight: 185, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1hXNK0c1yacED6MwFQ9QY-7cekkRhEfEC/view")
c11 = Challenger.create(first_name: 'Antonio', last_name: 'Nogueira',weight: 240, height: 75, champion_status: false, img_url:"https://drive.google.com/file/d/1n5ft6u1L6E49ptq32V6ErFjZp-OW0KFP/view")
c12 = Challenger.create(first_name: 'Matt', last_name: 'Hughes',weight: 170, height: 69, champion_status: false, img_url:"https://drive.google.com/file/d/1EYfZBrOvhxpGuLBPRb_qq45jsVV7yduf/view")
c13 = Challenger.create(first_name: 'Chuck', last_name: 'Liddell',weight: 205, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1UGZPdXNuAU0SizDCisFnkiSiWEeJlIaY/view")
c14 = Challenger.create(first_name: 'Masakatsu', last_name: 'Funaki',weight: 209, height: 72, champion_status: false, img_url:"https://drive.google.com/file/d/16fXb_M5ImW2p-0efH24WmqFeV_MYwQh1/view")
c15 = Challenger.create(first_name: 'Alistair', last_name: 'Overeem',weight: 260, height: 76, champion_status: false, img_url:"https://drive.google.com/file/d/1ifuK2LbyHQTXy0mkTIuAuWxDntZvZnR8/view")
c15 = Challenger.create(first_name: 'Francis', last_name: 'Ngannou',weight: 250, height: 76, champion_status: false, img_url:"https://drive.google.com/file/d/14QamItPoy7tdqFKsYfm5UzkTj-wizITX/view")
c16 = Challenger.create(first_name: 'Fedor', last_name: 'Emelianenko',weight: 223, height: 72, champion_status: false, img_url:"https://drive.google.com/file/d/1LNbziguzI7ogyl6_jnUiSQM89NzKQFGF/view")
c17 = Challenger.create(first_name: 'Randy', last_name: 'Couture',weight: 203, height: 61, champion_status: false, img_url:"https://drive.google.com/file/d/1BO6h7gmthyagNEbHnO4q7cfA3RBbnjiu/view")
c18 = Challenger.create(first_name: 'Nick', last_name: 'Diaz',weight: 155, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1k_O4XtlDyOFGfQaCQPrQb3g0H9qfJ0rC/view")
c19 = Challenger.create(first_name: 'Kamaru', last_name: 'Usman',weight: 170, height: 72, champion_status: true, img_url:"https://drive.google.com/file/d/1Dz_aLvuPvHGuwJu1rIK2FK1xXM0Ff-c4/view")
c20 = Challenger.create(first_name: 'Lyoto', last_name: 'Machida',weight: 185, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1WJ7moDbxj8APH_vrQr2s9FytPsvIpme_/view")
c21 = Challenger.create(first_name: 'Vitor', last_name: 'Belfort',weight: 185, height: 72, champion_status: false, img_url:"https://drive.google.com/file/d/1qrF7KAKnxU0-AJ-NSw4b8dwWdHlftFpi/view")
c22 = Challenger.create(first_name: 'Tim', last_name: 'Sylvia',weight: 265, height: 80, champion_status: false, img_url:"https://drive.google.com/file/d/1elRMpqFzudoUHsOJQDdKXmQn-K3qzXX1/view")
c23 = Challenger.create(first_name: 'Royce', last_name: 'Gracie',weight: 176, height: 72, champion_status: false, img_url:"https://drive.google.com/file/d/15997PfQisTlNR3bAaQ-X6557WGCnndao/view")
c24 = Challenger.create(first_name: 'BJ', last_name: 'Penn',weight: 145, height: 69, champion_status: false, img_url:"https://drive.google.com/file/d/1CkxxtwZdE1eRJ9q-ZpChT2wCTxAkgYcC/view")
c25 = Challenger.create(first_name: 'Rich', last_name: 'Franklin',weight: 185, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1ByLTF-ehv8OB251meWTPF7TgRg74uXUZ/view")
c26 = Challenger.create(first_name: 'Bas', last_name: 'Rutten',weight: 205, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1cigxGKvNADxS5glOwO9EW1tFOGdW4OcV/view")
c27 = Challenger.create(first_name: 'Israel', last_name: 'Adesanya',weight: 185, height: 76, champion_status: true, img_url:"https://drive.google.com/file/d/1en4m_ToIyeiBwEAlUK3_qGmwRfE_TmYu/view")
c28 = Challenger.create(first_name: 'Khabib', last_name: 'Nurmagomedov',weight: 155, height: 70, champion_status: true, img_url:"https://drive.google.com/file/d/17Oy6eGWZ6L_rjfRPTlDHbjFROArr0X4d/view")
c29 = Challenger.create(first_name: 'Justin', last_name: 'Gaethje',weight: 155, height: 71, champion_status: false, img_url:"https://drive.google.com/file/d/1io9fpOB7_2MOmt41Krqd_MZOtqLERHnf/view")
c30 = Challenger.create(first_name: 'Tony', last_name: 'Ferguson',weight: 155, height: 71, champion_status: false, img_url:"https://drive.google.com/file/d/1hB22F0ZVcnV2bLKTrzQyTpM8OSqFSZVm/view")
c31 = Challenger.create(first_name: 'Conor', last_name: 'McGregor',weight: 145, height: 69, champion_status: false, img_url:"https://drive.google.com/file/d/1RpHY8wigkmhBIdo8kOf0lspeTZxKb7_N/view")
c32 = Challenger.create(first_name: 'Demetrius', last_name: 'Johnson',weight: 135, height: 63, champion_status: false, img_url:"https://drive.google.com/file/d/1oV0rfI3VFLH35kOp3S4zXG7VoohX9TNN/view")
c33 = Challenger.create(first_name: 'Max', last_name: 'Holloway',weight: 146, height: 71, champion_status: false, img_url:"https://drive.google.com/file/d/16BQFpWsHavfnW73akIeVVEC4b299FzaE/view")
c34 = Challenger.create(first_name: 'Alex', last_name: 'Volkanovski',weight: 145, height: 66, champion_status: false, img_url:"https://drive.google.com/file/d/1JRE-EKePCKhzQYeXZN7mHrG7g1kMWWM2/view")
c35 = Challenger.create(first_name: 'Edson', last_name: 'Barboza',weight: 155, height: 71, champion_status: false, img_url:"https://drive.google.com/file/d/1EW06h_RkVpUzvyUsmVnPhCfRLvljNMMO/view")
c36 = Challenger.create(first_name: 'Henry', last_name: 'Cejudo',weight: 135, height: 64, champion_status: true, img_url:"https://drive.google.com/file/d/1OLuILqd4ZNAKr5RU1emxjxn99_7s9TBr/view")
c37 = Challenger.create(first_name: 'Frankie', last_name: 'Edgar',weight: 145, height: 66, champion_status: false, img_url:"https://drive.google.com/file/d/131Pj6T6g_IRjdN0zVFDPmLAHwvPLWLJa/view")
c38 = Challenger.create(first_name: 'Eddie', last_name: 'Alvarez',weight: 155, height: 69, champion_status: false, img_url:"https://drive.google.com/file/d/1Zx8wtKJp2r3rPyRny-TO91AF0GeZyk6A/view")
c39 = Challenger.create(first_name: 'Zabit', last_name: 'Magomedsharipov',weight: 145, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1pTF4CYzPJq0T7vk821o6U7udhjPzJv7d/view")
c40 = Challenger.create(first_name: 'Islam', last_name: 'Makhachev',weight: 155, height: 70, champion_status: false, img_url:"https://drive.google.com/file/d/1kQR_LZR725J39rdDyRFtJO-8VgYz47O6/view")
c41 = Challenger.create(first_name: 'Alexander', last_name: 'Volkov',weight: 250, height: 79, champion_status: false, img_url:"https://drive.google.com/file/d/1e0An-4xoxOBtIOrVNnSZlefMAt6Hu3Vo/view")
c42 = Challenger.create(first_name: 'Dominick', last_name: 'Reyes',weight: 205, height: 76, champion_status: false, img_url:"https://drive.google.com/file/d/1nTDCMnK8ZiZCaeOiyPEWK16spvMHT0V2/view")
c43 = Challenger.create(first_name: 'Paulo', last_name: 'Costa',weight: 185, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/12ItG9zSGEYEwstj8IJCTAJnOuWlaW2q0/view")
c44 = Challenger.create(first_name: 'Tyron', last_name: 'Woodley',weight: 170, height: 69, champion_status: false, img_url:"https://drive.google.com/file/d/1liiuDUZQZi2Rds27JoHfZNM6TE2fiXMc/view")
c45 = Challenger.create(first_name: 'Takanori', last_name: 'Gomi',weight: 155, height: 68, champion_status: false, img_url:"https://drive.google.com/file/d/1dAB8WrLMHHiK-OyaV91i64oz9mzQHJEZ/view")
c46 = Challenger.create(first_name: 'Thiago', last_name: 'Santos',weight: 185, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1z72KC5nQyEr8tqEQTHBadjx80yhhAy6Q/view")
c47 = Challenger.create(first_name: 'Marlon', last_name: 'Moraes',weight: 135, height: 66, champion_status: false, img_url:"https://drive.google.com/file/d/1DUxLKGj0fyKWVeKLw6ZlgYxms0Oq287x/view")
c48 = Challenger.create(first_name: 'Cain', last_name: 'Velasquez',weight: 243, height: 73, champion_status: false, img_url:"https://drive.google.com/file/d/1NDgoIkLXqMOUu0m3EtbQTfpeomXNiMvs/view")
c49 = Challenger.create(first_name: 'Chris', last_name: 'Weidman',weight: 186, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1QxoDntkOsu0NXG4XF5GVC4cyFRkCYtcZ/view")
c50 = Challenger.create(first_name: 'Gegard', last_name: 'Mousasi',weight: 185, height: 74, champion_status: false, img_url:"https://drive.google.com/file/d/1mBme_R-C99OKpZyA77_WHdZs6kLlwfcv/view")


u1 = User.create(username: 'Yannick')
u2 = User.create(username: 'Richard')

Match.create(fighter_id: f1.id, challenger_id: c2.id, user_id: u1.id, venue: "T-Mobile Arena", comment: "Going to be a dope fight!")
Match.create(fighter_id: f11.id, challenger_id: c8.id, user_id: u1.id, venue: "Staples Center", comment: "Cool!")
Match.create(fighter_id: f9.id, challenger_id: c10.id, user_id: u2.id, venue: "Toyota Center", comment: "Nice")
Match.create(fighter_id: f28.id, challenger_id: c29.id, user_id: u2.id, venue: "Fight Island", comment: "Fight")